import type { Metadata } from "next";
import Providers from "@/styles/Providers";
import GlobalStyles from "@/styles/GlobalStyles";
import { Noto_Sans_KR } from "next/font/google";
import { Footer } from "@/components/organisms/Footer";
import { CommonLayout } from "@/components/templates/layout/CommonLayout";
import { Header } from "@/components/organisms/Header";

const noto_sans_kr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={noto_sans_kr.className}>
      <body>
        <Providers>
          <Header
            menus={[
              { label: "About Me", value: "about-me" },
              { label: "Projects", value: "projects" },
            ]}
          />
          <GlobalStyles />
          {children}
          <Footer size="medium" />
        </Providers>
      </body>
    </html>
  );
}
