import type { Metadata } from "next";
import ThemeToggle from "@/components/atoms/ThemeToggle";
import Providers from "@/styles/Providers";
import GlobalStyles from "@/styles/GlobalStyles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <GlobalStyles />
          <ThemeToggle />
          {children}
        </Providers>
      </body>
    </html>
  );
}
